coverage:
  status:
    project:
      default:
        paths:
          - "backend/"
    patch: off

ignore:
  - "backend/legacy_agents/*"
  - "backend/test/*"
  - "backend/production_database_setup.py"