services:
  api:
    build:
      context: .
      dockerfile: ./backend/docker_utils/dockerfiles/api.dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/agent_games
      - VALIDATOR_URL=http://validator:8001
      - SIMULATOR_URL=http://simulator:8002
      - SECRET_KEY=${SECRET_KEY:-default_secret_key}
      - DATABASE_URL=${DATABASE_URL:-postgresql+psycopg://postgres:local_pw@postgres:5432/agent_games}
      - DB_ENVIRONMENT=${DB_ENVIRONMENT:-production}
    depends_on:
      postgres:
        condition: service_healthy
      validator:
        condition: service_healthy
      simulator:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./backend:/agent_games/backend
      - ./logs/api.log:/agent_games/logs/api.log
      - ./logs/validator.log:/agent_games/logs/validator.log:ro
      - ./logs/simulator.log:/agent_games/logs/simulator.log:ro
    mem_limit: 400m
    mem_reservation: 200m
    pids_limit: 50
    profiles: ["prod", "dev", "test"]

  validator:
    build:
      context: .
      dockerfile: ./backend/docker_utils/dockerfiles/validator.dockerfile
    ports:
      - "8001:8001"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/agent_games
      - DB_ENVIRONMENT=${DB_ENVIRONMENT:-production}
      - SECRET_KEY=${SECRET_KEY:-default_secret_key}
      - DATABASE_URL=${DATABASE_URL:-postgresql+psycopg://postgres:local_pw@postgres:5432/agent_games}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - ./logs/validator.log:/agent_games/logs/validator.log
    mem_limit: 500m
    mem_reservation: 200m
    pids_limit: 50
    profiles: ["prod", "dev", "test"]

  simulator:
    build:
      context: .
      dockerfile: ./backend/docker_utils/dockerfiles/simulator.dockerfile
    ports:
      - "8002:8002"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/agent_games
      - DB_ENVIRONMENT=${DB_ENVIRONMENT:-production}
      - SECRET_KEY=${SECRET_KEY:-default_secret_key}
      - DATABASE_URL=${DATABASE_URL:-postgresql+psycopg://postgres:local_pw@postgres:5432/agent_games}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - ./logs/simulator.log:/agent_games/logs/simulator.log
    mem_limit: 500m
    mem_reservation: 200m
    pids_limit: 50
    profiles: ["prod", "dev", "test"]

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-local_pw}
      POSTGRES_DB: agent_games
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d agent_games"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    mem_limit: 700m
    mem_reservation: 300m
    profiles: ["prod", "dev"]

  postgres_test:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      # Hardcoded test database credentials - no secrets needed
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test_db_password
      POSTGRES_DB: agent_games_test
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d agent_games_test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    mem_limit: 700m
    mem_reservation: 300m
    profiles: ["test"]

volumes:
  postgres_data:
  postgres_test_data: