services:
  validator:
    build:
      context: .
      dockerfile: ./backend/docker_utils/dockerfiles/validator.dockerfile
    network_mode: "host"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/agent_games
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    env_file:
      - ./backend/.env
    mem_limit: 500m
    mem_reservation: 200m
    pids_limit: 50

  simulator:
    build:
      context: .
      dockerfile: ./backend/docker_utils/dockerfiles/simulator.dockerfile
    network_mode: "host"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/agent_games
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    env_file:
      - ./backend/.env
    mem_limit: 500m
    mem_reservation: 200m
    pids_limit: 50