[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "agent_games"
version = "0.1.0"
requires-python = ">=3.10"

[tool.setuptools]
packages = ["backend"]
package-dir = {""= "."}