FROM python:3.12 as builder

WORKDIR /agent_games

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip install orjson
COPY requirements.txt .
RUN pip install -r requirements.txt


# Deriving the latest base image
FROM python:3.12
COPY --from=builder /opt/venv /opt/venv

# Install curl and Rust
RUN apt-get update && apt-get install -y curl
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
ENV PATH="/opt/venv/bin:$PATH"

# Copy files
COPY games /agent_games/games
COPY requirements.txt /agent_games
COPY models_db.py /agent_games
COPY utils.py /agent_games
COPY config.py /agent_games
COPY auth.py /agent_games
COPY dockerfile_script.py /agent_games

# Set working directory
WORKDIR /agent_games

# Set the entrypoint
ENTRYPOINT ["python", "dockerfile_script.py"]