import React, { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { useDispatch, useSelector } from "react-redux";

import { setToken } from "../../slices/authSlice";
import { setCurrentTeam } from "../../slices/teamsSlice";
import { getTerms } from "../Shared/terminology";

// Public landing page for a one-time password-reset link generated by the
// team's institution (/reset/:resetToken). Shows who the link is for, takes a
// new password twice, then logs the student straight into their existing
// account. A real <form> submit (plus the Credential Management API where
// available) is what makes browsers offer to save the new credentials.
function TeamPasswordReset() {
  const { resetToken } = useParams();
  const navigate = useNavigate();
  const dispatch = useDispatch();
  const apiUrl = useSelector((state) => state.settings.agentApiUrl);

  const [info, setInfo] = useState(null);
  const [pageError, setPageError] = useState("");
  const [passwords, setPasswords] = useState({ password: "", confirm: "" });
  const [formError, setFormError] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [done, setDone] = useState(false);

  // Wording comes from the owning institution: visitors here are logged out.
  const T = getTerms(Boolean(info?.is_teacher));

  useEffect(() => {
    const fetchInfo = async () => {
      if (!resetToken) return;
      try {
        const response = await fetch(
          `${apiUrl}/user/password-reset-info/${resetToken}`
        );
        const data = await response.json();
        if (response.ok) {
          setInfo(data);
        } else {
          setPageError(
            data.detail || "This password reset link is invalid or has expired"
          );
        }
      } catch {
        setPageError("Network error — please try again");
      }
    };

    fetchInfo();
  }, [resetToken, apiUrl]);

  const handleChange = (e) => {
    setPasswords((prev) => ({ ...prev, [e.target.name]: e.target.value }));
    setFormError("");
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!passwords.password.trim()) {
      setFormError("Please enter a new password");
      return;
    }
    if (passwords.password !== passwords.confirm) {
      setFormError("Passwords do not match");
      return;
    }

    setSubmitting(true);
    try {
      const response = await fetch(`${apiUrl}/user/reset-team-password`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          reset_token: resetToken,
          password: passwords.password,
        }),
      });
      const data = await response.json();

      if (!response.ok) {
        setFormError(data.detail || "Failed to reset password");
        return;
      }

      dispatch(setToken(data.access_token));
      dispatch(setCurrentTeam(data.team_name));

      // Chrome-family browsers can store the credentials directly; elsewhere
      // the form submission above triggers the browser's own save prompt.
      try {
        if (window.PasswordCredential) {
          const cred = new window.PasswordCredential({
            id: data.team_name,
            name: data.team_name,
            password: passwords.password,
          });
          await navigator.credentials.store(cred);
        }
      } catch {
        // Best-effort only — saving credentials is never required.
      }

      setDone(true);
    } catch {
      setFormError("Network error — please try again");
    } finally {
      setSubmitting(false);
    }
  };

  const inputClasses = `w-full px-4 py-2 text-lg rounded-lg transition-all duration-200
    border border-ui-light/20 focus:outline-none focus:ring-1 focus:ring-primary/30 focus:border-primary/30`;

  return (
    <div className="min-h-screen pt-16 flex flex-col items-center justify-center bg-ui-lighter">
      <div className="w-full max-w-md px-4">
        <div className="bg-white rounded-lg shadow-lg p-8">
          {info ? (
            <>
              <div className="mb-6 text-center">
                <p className="text-sm uppercase tracking-wide text-ui-dark/60">
                  {info.institution_name || "Agent Games"}
                </p>
                <h1 className="text-2xl font-bold text-ui-dark">
                  {info.team_name}
                </h1>
                <p className="text-ui-dark/70">
                  {done ? "Password updated" : "Set a new password"}
                </p>
              </div>

              {done ? (
                <div className="space-y-4 text-center">
                  <p className="text-ui-dark">
                    {`You're logged in as `}
                    <span className="font-semibold">{info.team_name}</span>
                    {`. All your previous work is still there.`}
                  </p>
                  <p className="text-sm text-ui-dark/60">
                    If your browser offers to save your password, choose Save
                    so you can log in easily next time.
                  </p>
                  <button
                    onClick={() => navigate("/TeamHome")}
                    className="w-full py-3 px-4 text-lg font-medium text-white bg-primary hover:bg-primary-hover rounded-lg transition-colors duration-200"
                  >
                    Continue to your workspace
                  </button>
                </div>
              ) : (
                <form onSubmit={handleSubmit} className="space-y-5">
                  {/* Present but read-only so password managers save the
                      credentials under the team name. */}
                  <input
                    type="text"
                    name="username"
                    autoComplete="username"
                    value={info.team_name}
                    readOnly
                    hidden
                  />

                  <div className="space-y-2">
                    <label className="block text-lg font-medium text-ui-dark">
                      New password:
                    </label>
                    <input
                      type="password"
                      name="password"
                      autoComplete="new-password"
                      value={passwords.password}
                      onChange={handleChange}
                      className={inputClasses}
                      placeholder="Choose a new password"
                      autoFocus
                    />
                  </div>

                  <div className="space-y-2">
                    <label className="block text-lg font-medium text-ui-dark">
                      Confirm password:
                    </label>
                    <input
                      type="password"
                      name="confirm"
                      autoComplete="new-password"
                      value={passwords.confirm}
                      onChange={handleChange}
                      className={inputClasses}
                      placeholder="Type it again"
                    />
                  </div>

                  <button
                    type="submit"
                    disabled={submitting}
                    className="w-full py-3 px-4 text-lg font-medium text-white bg-primary hover:bg-primary-hover rounded-lg transition-colors duration-200 disabled:bg-ui-light disabled:cursor-not-allowed"
                  >
                    {submitting ? "Saving..." : "Set password and log in"}
                  </button>

                  {formError && (
                    <p className="text-danger text-center">{formError}</p>
                  )}

                  <p className="text-center text-sm text-ui-dark/60">
                    {`This logs you into your existing ${T.team} account — your work is kept.`}
                  </p>
                </form>
              )}
            </>
          ) : pageError ? (
            <div className="text-center text-danger p-4">
              <p>{pageError}</p>
              <p className="mt-2">
                <a href="/" className="text-primary hover:text-primary-hover">
                  Return to home page
                </a>
              </p>
            </div>
          ) : (
            <div className="text-center p-4">
              <p className="text-ui-dark/60">Loading...</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

export default TeamPasswordReset;
