#!/usr/bin/env bash
# Idempotent deploy of the agent-validation Lambda.
#
#   aws-vault exec <admin-profile> -- ./backend/validation_lambda/deploy.sh [--smoke]
#
# Creates the IAM role on first run (logs-only: the sandbox guarantee is an
# execution role with zero permissions beyond CloudWatch), then creates or
# updates the function from a staged zip: this folder's stdlib-only modules,
# the whole backend/games tree, and a GENERATED backend/config.py stub
# (ROOT_DIR + GAMES only — the real config load_dotenv()s secrets at import
# time and must never ship). client.py is deliberately excluded — it imports
# boto3 and never ships.
#
# --smoke invokes three payloads and asserts the envelopes, including the
# exact timeout message for a spinner.
set -euo pipefail

FUNCTION_NAME="agent-games-validation"
ROLE_NAME="agent-games-validation-role"
REGION="ap-southeast-2"
# Matches the backend image (python:3.14-alpine) — no interpreter skew
# between the API, the tests, and the deployed function.
RUNTIME="python3.14"
ARCH="arm64"
# 1769MB = 1 full vCPU on Lambda (CPU scales with memory). The 5s soft
# limit is wall-clock and the per-game validation_simulations counts were
# benchmarked on cpus:1.0 — less memory here means less CPU and false
# timeouts, not just less RAM.
MEMORY_MB=1769
# 6.2s in-child deadline + fork + cold-start import of the games tree.
TIMEOUT_S=8
RESERVED_CONCURRENCY=10
HANDLER="backend.validation_lambda.handler.lambda_handler"

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
STAGE="$(mktemp -d)"
ZIP_FILE="$(mktemp -d)/validation_lambda.zip"

echo "==> Staging zip contents (modules + games tree + generated config stub)"
mkdir -p "$STAGE/backend/validation_lambda"
cp "$REPO_ROOT/backend/__init__.py" "$STAGE/backend/"
for module in __init__ executor handler local_run; do
  cp "$REPO_ROOT/backend/validation_lambda/$module.py" "$STAGE/backend/validation_lambda/"
done
(
  cd "$REPO_ROOT"
  find backend/games -name '*.py' -not -path '*/__pycache__/*' | while read -r f; do
    mkdir -p "$STAGE/$(dirname "$f")"
    cp "$f" "$STAGE/$f"
  done
)
cat > "$STAGE/backend/config.py" <<'PY'
"""Stdlib-only stand-in for backend/config.py, generated by deploy.sh.

The games tree imports only ROOT_DIR and GAMES from backend.config; the real
module load_dotenv()s secrets at import time and must never ship in the zip.
Discovery mirrors config._discover_games (and local_run._install_config_stub),
so adding a game needs nothing beyond redeploying.
"""

import os

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))


def _discover_games(games_dir):
    if not os.path.isdir(games_dir):
        return []
    games = []
    for entry in sorted(os.listdir(games_dir)):
        game_dir = os.path.join(games_dir, entry)
        if not os.path.isdir(game_dir):
            continue
        if entry.startswith("_") or entry.startswith("."):
            continue
        required = ["player.py", f"{entry}.py", "validation_players.py"]
        if all(os.path.isfile(os.path.join(game_dir, f)) for f in required):
            games.append(entry)
    return games


GAMES = _discover_games(os.path.join(ROOT_DIR, "games"))
PY
(
  cd "$STAGE"
  zip -qr "$ZIP_FILE" backend
)

echo "==> Ensuring IAM role $ROLE_NAME"
if ! aws iam get-role --role-name "$ROLE_NAME" >/dev/null 2>&1; then
  aws iam create-role \
    --role-name "$ROLE_NAME" \
    --assume-role-policy-document '{
      "Version": "2012-10-17",
      "Statement": [{
        "Effect": "Allow",
        "Principal": {"Service": "lambda.amazonaws.com"},
        "Action": "sts:AssumeRole"
      }]
    }' >/dev/null
  aws iam attach-role-policy \
    --role-name "$ROLE_NAME" \
    --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  echo "    created (waiting for propagation)"
fi
ROLE_ARN="$(aws iam get-role --role-name "$ROLE_NAME" --query Role.Arn --output text)"

if aws lambda get-function --function-name "$FUNCTION_NAME" --region "$REGION" >/dev/null 2>&1; then
  echo "==> Updating $FUNCTION_NAME"
  aws lambda update-function-code \
    --function-name "$FUNCTION_NAME" \
    --zip-file "fileb://$ZIP_FILE" \
    --region "$REGION" >/dev/null
  aws lambda wait function-updated --function-name "$FUNCTION_NAME" --region "$REGION"
  aws lambda update-function-configuration \
    --function-name "$FUNCTION_NAME" \
    --runtime "$RUNTIME" \
    --handler "$HANDLER" \
    --memory-size "$MEMORY_MB" \
    --timeout "$TIMEOUT_S" \
    --region "$REGION" >/dev/null
  aws lambda wait function-updated --function-name "$FUNCTION_NAME" --region "$REGION"
else
  echo "==> Creating $FUNCTION_NAME"
  # Fresh roles take a few seconds to become assumable by Lambda.
  for attempt in $(seq 1 10); do
    if aws lambda create-function \
      --function-name "$FUNCTION_NAME" \
      --runtime "$RUNTIME" \
      --architectures "$ARCH" \
      --handler "$HANDLER" \
      --role "$ROLE_ARN" \
      --memory-size "$MEMORY_MB" \
      --timeout "$TIMEOUT_S" \
      --zip-file "fileb://$ZIP_FILE" \
      --region "$REGION" >/dev/null 2>&1; then
      break
    fi
    if [ "$attempt" -eq 10 ]; then
      echo "create-function failed after 10 attempts" >&2
      exit 1
    fi
    echo "    role not assumable yet, retrying (${attempt}/10)"
    sleep 3
  done
  aws lambda wait function-active --function-name "$FUNCTION_NAME" --region "$REGION"
fi

aws lambda put-function-concurrency \
  --function-name "$FUNCTION_NAME" \
  --reserved-concurrent-executions "$RESERVED_CONCURRENCY" \
  --region "$REGION" >/dev/null

echo "==> Deployed $FUNCTION_NAME ($RUNTIME/$ARCH, ${MEMORY_MB}MB, ${TIMEOUT_S}s, concurrency $RESERVED_CONCURRENCY)"

if [ "${1:-}" != "--smoke" ]; then
  exit 0
fi

echo "==> Smoke tests"
OUT_DIR="$(mktemp -d)"

cat > "$OUT_DIR/pass_payload.json" <<'JSON'
{"kind":"validation","code":"from games.greedy_pig.player import Player\nclass CustomPlayer(Player):\n    def make_decision(self, game_state):\n        return 'bank'\n","game_name":"greedy_pig","team_name":"smoke"}
JSON
cat > "$OUT_DIR/construct_payload.json" <<'JSON'
{"kind":"validation","code":"x = 1\n","game_name":"greedy_pig","team_name":"smoke"}
JSON
cat > "$OUT_DIR/spin_payload.json" <<'JSON'
{"kind":"validation","code":"from games.greedy_pig.player import Player\nclass CustomPlayer(Player):\n    def make_decision(self, game_state):\n        while True:\n            pass\n","game_name":"greedy_pig","team_name":"smoke"}
JSON

invoke() {
  aws lambda invoke \
    --function-name "$FUNCTION_NAME" \
    --cli-binary-format raw-in-base64-out \
    --payload "file://$OUT_DIR/$1_payload.json" \
    --region "$REGION" \
    "$OUT_DIR/$1.json" >/dev/null
}

invoke pass
invoke construct
START=$(date +%s)
invoke spin
SPIN_SECS=$(( $(date +%s) - START ))

python3 - "$OUT_DIR" "$SPIN_SECS" <<'PY'
import json, sys
out_dir, spin_secs = sys.argv[1], int(sys.argv[2])
validation_keys = {"status", "message", "feedback", "simulation_results",
                   "duration_ms", "traceback", "stdout"}
timeout_msg = ("Your agent consumes too much time - validation did not "
               "finish within 5 seconds. "
               "The agent may be too slow or stuck in a loop.")

def load(name):
    with open(f"{out_dir}/{name}.json") as f:
        return json.load(f)

r = load("pass")
assert set(r) == validation_keys and r["status"] == "success", r
assert "smoke" in r["simulation_results"]["total_points"], r["simulation_results"]
r = load("construct")
assert set(r) == validation_keys and r["status"] == "error", r
assert r["message"].startswith("Failed to create player for team smoke"), r["message"]
r = load("spin")
assert set(r) == validation_keys and r["status"] == "error", r
assert r["message"] == timeout_msg, r["message"]
assert spin_secs <= 9, f"spinner took {spin_secs}s (hard kill not working?)"
print("smoke tests passed")
PY
