import os
from datetime import datetime
from enum import Enum as PyEnum
from typing import List, Optional

import bcrypt as _bcrypt
from sqlalchemy import JSON, Column, DateTime, Text
from sqlmodel import Field, Relationship, SQLModel

from backend.time_utils import utc_now

# Test runs set BCRYPT_ROUNDS=4 so runtime hashing costs ~1ms instead of ~170ms.
_BCRYPT_ROUNDS = int(os.environ.get("BCRYPT_ROUNDS", "12"))

# The holding pen every team lands in when it has no league: created once by
# init_db, guaranteed unique by League's unique name, and refused by
# delete_league. Keyed by name because the name is already how every caller
# finds it.
UNASSIGNED_LEAGUE_NAME = "unassigned"


def get_password_hash(password):
    if isinstance(password, str):
        password = password.encode("utf-8")
    return _bcrypt.hashpw(password, _bcrypt.gensalt(rounds=_BCRYPT_ROUNDS)).decode("utf-8")


def verify_password(plain_password, hashed_password):
    if isinstance(plain_password, str):
        plain_password = plain_password.encode("utf-8")
    if isinstance(hashed_password, str):
        hashed_password = hashed_password.encode("utf-8")
    return _bcrypt.checkpw(plain_password, hashed_password)


class TeamType(str, PyEnum):
    STUDENT = "student"
    AGENT = "agent"


class LeagueType(str, PyEnum):
    STUDENT = "student"
    AGENT = "agent"


class Owner(SQLModel, table=True):
    """The single account that runs this deployment.

    One row, created by the first-run setup endpoint rather than seeded, so a
    fresh clone has no default password to forget to change. Replaces the old
    Admin/Institution pair: with one tenant there is no platform operator
    standing above the organizer, so there is one account and one role.
    """

    id: Optional[int] = Field(default=None, primary_key=True)
    username: str = Field(unique=True, index=True)
    password_hash: str

    def set_password(self, password: str):
        self.password_hash = get_password_hash(password)

    def verify_password(self, password: str):
        return verify_password(password, self.password_hash)


class League(SQLModel, table=True):
    id: int = Field(primary_key=True, default=None)
    # Globally unique now that leagues have no owning tenant. This is also what
    # guarantees the 'unassigned' holding pen is a singleton.
    name: str = Field(unique=True, index=True)
    created_date: datetime = Field(sa_column=Column(DateTime(timezone=True)))
    expiry_date: datetime = Field(sa_column=Column(DateTime(timezone=True)))
    deleted_date: Optional[datetime] = Field(
        default=None, sa_column=Column(DateTime(timezone=True), nullable=True)
    )
    # Public lookup key for the shareable join page: unique so a duplicate token
    # can never shadow another league, indexed because every join hits it.
    signup_link: Optional[str] = Field(default=None, unique=True, index=True)
    game: str
    league_type: LeagueType = Field(default=LeagueType.STUDENT)
    school_league: bool = Field(default=False)
    schools_config: Optional[dict] = Field(
        default=None,
        sa_column=Column(JSON, nullable=True),
    )
    info_markdown: str = Field(default="", sa_column=Column(Text(), nullable=False, server_default=""))

    teams: List["Team"] = Relationship(
        back_populates="league",
        sa_relationship_kwargs={"passive_deletes": True},
    )
    simulation_results: List["SimulationResult"] = Relationship(
        back_populates="league",
        sa_relationship_kwargs={"passive_deletes": True},
    )


class Team(SQLModel, table=True):
    id: int = Field(primary_key=True)
    # Globally unique: with one tenant there is no scope to be unique within, and
    # uniqueness is what lets login resolve a name to exactly one row instead of
    # trying every match's password in turn.
    name: str = Field(unique=True, index=True)
    school_name: str
    password_hash: Optional[str] = None  # Optional for agent teams
    score: int = Field(default=0)
    color: str = Field(default="rgb(171,239,177)")
    league_id: int = Field(foreign_key="league.id", ondelete="CASCADE")
    team_type: TeamType = Field(default=TeamType.STUDENT)
    created_at: datetime = Field(
        default_factory=utc_now, sa_column=Column(DateTime(timezone=True))
    )
    # One-time password-reset link: generated by the owner and shared with the
    # student out-of-band, cleared when consumed. Regenerating replaces the
    # previous token, so a mis-shared link can be invalidated.
    password_reset_token: Optional[str] = Field(default=None, index=True)
    password_reset_expiry: Optional[datetime] = Field(
        default=None, sa_column=Column(DateTime(timezone=True))
    )

    league: League = Relationship(back_populates="teams")
    submission_attempts: List["SubmissionMetadata"] = Relationship(
        back_populates="team",
        sa_relationship_kwargs={"passive_deletes": True},
    )
    api_key: Optional["AgentAPIKey"] = Relationship(
        back_populates="team",
        sa_relationship_kwargs={"uselist": False, "passive_deletes": True},
    )

    def set_password(self, password: str):
        self.password_hash = get_password_hash(password)

    def verify_password(self, password: str):
        if not self.password_hash:  # Handle agent teams with no password
            return False
        return verify_password(password, self.password_hash)


class SubmissionMetadata(SQLModel, table=True):
    """One row per submission attempt, pass or fail. Drives rate limiting
    and hint availability. A linked Submission row == passed validation."""

    id: Optional[int] = Field(default=None, primary_key=True)
    team_id: int = Field(foreign_key="team.id", ondelete="CASCADE", index=True)
    # Nullable: an attempt can be recorded before the team has joined a league.
    # The cascade still fires whenever it is set.
    league_id: Optional[int] = Field(
        default=None, foreign_key="league.id", ondelete="CASCADE", nullable=True
    )
    timestamp: datetime = Field(sa_column=Column(DateTime(timezone=True)))
    duration_ms: Optional[float] = Field(default=None)
    hint_included: bool = Field(default=False)

    team: Team = Relationship(back_populates="submission_attempts")
    submission: Optional["Submission"] = Relationship(
        back_populates="meta",
        sa_relationship_kwargs={"uselist": False, "passive_deletes": True},
    )


class Submission(SQLModel, table=True):
    """Validated code only. 1:1 with SubmissionMetadata via unique FK."""

    id: Optional[int] = Field(default=None, primary_key=True)
    code: str = Field(sa_column=Column(Text()))  # Use Text for potentially long code
    timestamp: datetime = Field(sa_column=Column(DateTime(timezone=True)))
    # Rank against the game's validation bots (1 = best, competition ranking),
    # from the validation run's total_points. Not a league standing.
    ranking: Optional[int] = Field(default=None)
    metadata_id: int = Field(
        foreign_key="submissionmetadata.id", ondelete="CASCADE", unique=True, index=True
    )
    # `metadata` is reserved on SQLAlchemy declarative classes
    meta: SubmissionMetadata = Relationship(back_populates="submission")


class SimulationResult(SQLModel, table=True):
    id: int = Field(primary_key=True, default=None)
    league_id: int = Field(foreign_key="league.id", ondelete="CASCADE")
    timestamp: datetime = Field(sa_column=Column(DateTime(timezone=True)))
    published: bool = Field(default=False)
    num_simulations: int = Field(default=0)
    custom_rewards: str = Field(default="[10, 0, 0, 0, 0, 0, 0]")
    feedback_str: Optional[str] = Field(default=None, sa_column=Column(Text()))
    feedback_json: Optional[str] = Field(default=None, sa_column=Column(Text()))
    # Public lookup key for the shareable results page — unique and indexed for
    # the same reason as League.signup_link.
    publish_link: Optional[str] = Field(default=None, unique=True, index=True)

    league: League = Relationship(back_populates="simulation_results")
    simulation_results: List["SimulationResultItem"] = Relationship(
        back_populates="simulation_result",
        sa_relationship_kwargs={"passive_deletes": True},
    )


class SimulationResultItem(SQLModel, table=True):
    id: int = Field(primary_key=True, default=None)
    simulation_result_id: int = Field(
        foreign_key="simulationresult.id", ondelete="CASCADE"
    )
    # Indexed: this is the join column for every standings read.
    team_id: int = Field(foreign_key="team.id", ondelete="CASCADE", index=True)
    score: float = Field(default=0)
    custom_value1: Optional[float] = None
    custom_value2: Optional[float] = None
    custom_value3: Optional[float] = None
    custom_value1_name: Optional[str] = None
    custom_value2_name: Optional[str] = None
    custom_value3_name: Optional[str] = None

    simulation_result: SimulationResult = Relationship(
        back_populates="simulation_results"
    )
    team: Team = Relationship()


class AgentAPIKey(SQLModel, table=True):
    """Model for API key management"""

    id: int = Field(primary_key=True, default=None)
    key: str = Field(unique=True, index=True)
    team_id: int = Field(
        foreign_key="team.id", ondelete="CASCADE", unique=True
    )  # Ensures one API key per team
    created_at: datetime = Field(
        default_factory=utc_now, sa_column=Column(DateTime(timezone=True))
    )
    last_used: Optional[datetime] = Field(
        default=None, sa_column=Column(DateTime(timezone=True), nullable=True)
    )
    is_active: bool = Field(default=True)

    team: Team = Relationship(back_populates="api_key")


class AIProviderKey(SQLModel, table=True):
    """Stores API keys for external AI providers (OpenAI, etc.)"""

    id: Optional[int] = Field(default=None, primary_key=True)
    provider: str = Field(unique=True, index=True)  # e.g. "openai"
    api_key: str = Field(sa_column=Column(Text()))
    created_at: datetime = Field(
        default_factory=utc_now, sa_column=Column(DateTime(timezone=True))
    )
    updated_at: datetime = Field(
        default_factory=utc_now, sa_column=Column(DateTime(timezone=True))
    )
