name: Test, Coverage and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**' 

jobs:
  test_and_coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio httpx pytest-cov
        pip install -r requirements.txt

    - name: Run tests with coverage
      run: |
        cd backend
        pytest --cov=. --cov-report=xml --cov-report=term tests/

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: SanjinDedic/agent_games
        directory: ./backend
        flags: backend
        fail_ci_if_error: true
        verbose: true

  deploy:
    needs: test_and_coverage  # This ensures deployment only runs after successful tests
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'  # Only deploy on main branch pushes
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USERNAME: ${{ secrets.EC2_USERNAME }}
        KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        SERVICE_TOKEN: ${{ secrets.SERVICE_TOKEN }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "bash -s" << 'ENDSSH' "$SERVICE_TOKEN" "$SECRET_KEY"
          SERVICE_TOKEN=$1
          SECRET_KEY=$2
          
          echo "Starting deployment..."
          
          # Ensure Docker is running
          if ! sudo systemctl is-active --quiet docker; then
            echo "Starting Docker service..."
            sudo systemctl start docker
          fi

          # Setup directories with correct structure
          mkdir -p ~/main_application/agent_games/backend
          cd ~/main_application/agent_games

          # Clean old deployment
          sudo docker system prune -f
          sudo docker image prune -af
          
          # Clone and copy files with correct structure
          tmp_dir=$(mktemp -d)
          git clone --depth 1 --filter=blob:none --sparse https://github.com/SanjinDedic/agent_games.git "$tmp_dir"
          cd "$tmp_dir"
          git sparse-checkout set backend

          # Copy backend contents to the correct directory
          cp -r backend/* ~/main_application/agent_games/backend/
          cp -r backend/.[^.]* ~/main_application/agent_games/backend/ 2>/dev/null || true

          # Clean up temporary directory
          rm -rf "$tmp_dir"

          # Change to backend directory for Docker builds
          cd ~/main_application/agent_games/backend

          # Build Docker containers
          echo "Building simulator container..."
          sudo docker build -t simulator -f docker_utils/dockerfiles/simulator.dockerfile .
          
          echo "Building validator container..."
          sudo docker build -t validator -f docker_utils/dockerfiles/validator.dockerfile .
          
          # Stop any existing containers
          sudo docker stop validator simulator || true
          sudo docker rm validator simulator || true
          
          # Start new containers with environment variables
          sudo docker run -d --name validator \
            --network=host \
            -v $(pwd):/agent_games/backend:ro \
            -e SERVICE_TOKEN="$SERVICE_TOKEN" \
            -e SECRET_KEY="$SECRET_KEY" \
            validator

          sudo docker run -d --name simulator \
            --network=host \
            -v $(pwd):/agent_games/backend:ro \
            -e SERVICE_TOKEN="$SERVICE_TOKEN" \
            -e SECRET_KEY="$SECRET_KEY" \
            simulator

          # Restart the Agent Games service using PM2
          cd ~/main_application
          pm2 restart Agent_Games
          
          # Debug line to confirm successful deployment
          touch successful_deployment
          echo "deploy successful" > successful_deployment
          
          # Echo docker container status
          echo "Docker container status:"
          sudo docker ps | grep -E 'validator|simulator'
          
          echo "Deployment completed"
        ENDSSH